###################
### MY PROGRAMS ###
###################

$terminal = alacritty
$fileManager = dolphin
$menu = ~/.config/quickshell/toggle-app-launcher
$calendar = ~/.config/quickshell/toggle-calendar
$powermenu = ~/.config/quickshell/toggle-power-menu
$themeswitcher = ~/.config/quickshell/toggle-theme-switcher
$browser = librewolf
$secondbrowser = qutebrowser
$editor = nvim
